// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $index from './routes/index.tsx';
import * as $profile from './routes/profile.tsx';
import * as $sign_in from './routes/sign-in.tsx';
import * as $CustomSignOutButton from './islands/CustomSignOutButton.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/index.tsx': $index,
    './routes/profile.tsx': $profile,
    './routes/sign-in.tsx': $sign_in,
  },
  islands: {
    './islands/CustomSignOutButton.tsx': $CustomSignOutButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
